/*
 * ManageProductCatalogJPanel.java
 *
 * Created on September 24, 2008, 2:40 PM
 */
package UserInterface.AirlinerManagement;

import UserInterface.AirlinerManagement.Airfleetmanage.ManageFleetJPanelPart;
import Business.Airplane;
import Business.Airliner;
import Business.AirlinerDirectory;
import Business.AirplaneDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import Business.FleetDirectory;
import Business.Flight;
import Business.FlightDirectory;
import UserInterface.TravelAgencyManagement.AddAirliner;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rushabh
 */
public class ManageAirlinerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Airliner airliner;  
    AirlinerDirectory airlinerDirectory;
    FleetDirectory fleetDirectory;
    String s;
    Airplane airplane;
    AirplaneDirectory airplaneDirectory;
    Flight flight;
    FlightDirectory flightDirectory;
    Customer customer;
    CustomerDirectory customerDirectory;
            
    /** Creates new form ManageProductCatalogJPanel */
    public ManageAirlinerJPanel(JPanel upc, Airliner s,AirlinerDirectory ad,FleetDirectory fleetDirectory,AirplaneDirectory airplaneDirectory,FlightDirectory flightDirectory, Customer customer,CustomerDirectory customerDirectory) {
        initComponents();
        userProcessContainer = upc;
        airliner = s;
        airlinerDirectory=ad;
        this.fleetDirectory=fleetDirectory;
        this.airplane=airplane;
        this.airplaneDirectory=airplaneDirectory;
        this.flightDirectory=flightDirectory;
        this.customer=customer;
        this.customerDirectory=customerDirectory;
//        sNameTextField.setText(airliner.getAirlinerName());
        refreshTable();
    }
    
    public void refreshTable() {
        int rowCount = airlinerCatalog.getRowCount();
        DefaultTableModel model = (DefaultTableModel)airlinerCatalog.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Airliner p : airlinerDirectory.getAirlinerDirect()) {
            Object row[] = new Object[3];
            row[0] = p;
            row[1] = p.getCodeName();
            row[2] = p.getAirlinerStarRating();
            model.addRow(row);
            }
        }

    public void refreshTable(AirlinerDirectory airl) {
        AirlinerDirectory airlinerDirectory=airl;
        int rowCount = airlinerCatalog.getRowCount();
        DefaultTableModel model = (DefaultTableModel)airlinerCatalog.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Airliner p : airlinerDirectory.getAirlinerDirect()) {
            Object row[] = new Object[3];
            row[0] = p;
            row[1] = p.getCodeName();
            row[2] = p.getAirlinerStarRating();
            model.addRow(row);
            }
        }
    
 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airlinerCatalog = new javax.swing.JTable();
        viewPButton = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();
        delButton5 = new javax.swing.JButton();
        searchPButton1 = new javax.swing.JButton();
        viewfleetButton = new javax.swing.JButton();
        codenameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resumePButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Airliner Directory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        airlinerCatalog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        airlinerCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Airliner Name", "AL codeName", "AL starRating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airlinerCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 500, 170));

        viewPButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewPButton.setText("View Airliner Detail >>");
        viewPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPButtonActionPerformed(evt);
            }
        });
        add(viewPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 220, -1));

        backButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });
        add(backButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, -1));

        delButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delButton5.setText("Delete Airliner");
        delButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButton5ActionPerformed(evt);
            }
        });
        add(delButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 190, -1));

        searchPButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchPButton1.setText("Search");
        searchPButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPButton1ActionPerformed(evt);
            }
        });
        add(searchPButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 90, -1));

        viewfleetButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewfleetButton.setText("View Airliner's Fleet >>");
        viewfleetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewfleetButtonActionPerformed(evt);
            }
        });
        add(viewfleetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 220, -1));

        codenameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codenameFieldActionPerformed(evt);
            }
        });
        add(codenameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 30));

        jLabel3.setText("CodeName:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        resumePButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resumePButton3.setText("Resume");
        resumePButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumePButton3ActionPerformed(evt);
            }
        });
        add(resumePButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 100, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void viewPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPButtonActionPerformed
        // TODO add your handling code here:
        int row = airlinerCatalog.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airliner p = (Airliner)airlinerCatalog.getValueAt(row, 0);
        ViewAirlinerJPanel vpdjp = new ViewAirlinerJPanel(userProcessContainer, p);
        userProcessContainer.add("ViewProductDetailJPanelSupplier", vpdjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPButtonActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton4ActionPerformed

    private void delButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButton5ActionPerformed
        // TODO add your handling code here:
        int row = airlinerCatalog.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airliner p = (Airliner)airlinerCatalog.getValueAt(row, 0);
        airlinerDirectory.removeAirliner(p);
        refreshTable();
    }//GEN-LAST:event_delButton5ActionPerformed

    private void searchPButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPButton1ActionPerformed
        // TODO add your handling code here:
        try{
            AirlinerDirectory ald=new AirlinerDirectory();
        int row=airlinerCatalog.getRowCount();
        if(codenameField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please input search key words");
        }else if(row==0){
            JOptionPane.showMessageDialog(null, "Cannot do research! The table is empty.");
        }else{ 
                ArrayList<Airliner> AirlinerDirectory = new ArrayList<Airliner>();
                ald.setAirlinerDirect(this.airlinerDirectory.searchAirliner(codenameField.getText()));
                refreshTable(ald);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Try to input correctly.");
        }
        
        
    }//GEN-LAST:event_searchPButton1ActionPerformed

    private void viewfleetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewfleetButtonActionPerformed
        // TODO add your handling code here:
        int row = airlinerCatalog.getSelectedRow();       
        Airliner p = null;//(Airliner)airlinerCatalog.getValueAt(row, 1); 
        String s=String.valueOf(airlinerCatalog.getValueAt(row, 0));
        ManageFleetJPanelPart mf = new ManageFleetJPanelPart(userProcessContainer,p ,fleetDirectory,airplane,airplaneDirectory,flight,flightDirectory,customer,customerDirectory,s);
        userProcessContainer.add("ManageFleetJPanelPart", mf);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_viewfleetButtonActionPerformed

    private void codenameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codenameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codenameFieldActionPerformed

    private void resumePButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumePButton3ActionPerformed
        // TODO add your handling code here:
        refreshTable();
        
    }//GEN-LAST:event_resumePButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlinerCatalog;
    private javax.swing.JButton backButton4;
    private javax.swing.JTextField codenameField;
    private javax.swing.JButton delButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resumePButton3;
    private javax.swing.JButton searchPButton1;
    private javax.swing.JButton viewPButton;
    private javax.swing.JButton viewfleetButton;
    // End of variables declaration//GEN-END:variables
}
