/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package UserInterface.AirlinerManagement.AirFlightManage;

import UserInterface.AirlinerManagement.Airfleetmanage.*;
import Business.Airplane;
import Business.Airliner;
import Business.Fleet;
import Business.FleetDirectory;
import Business.Flight;
import Business.FlightDirectory;
import UserInterface.TravelAgencyManagement.ManageAirliners;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Rushabh
 */
public class CreateNewFlightJPanel extends javax.swing.JPanel {

    FleetDirectory fleetDirectory;
    JPanel userProcessContainer;
    Flight flight;
    FlightDirectory flightDirectory;
    
    /** Creates new form CreateProductJPanel */
    public CreateNewFlightJPanel(JPanel userProcessContainer, FleetDirectory fleetDirectory,Flight flight,FlightDirectory flightDirectory){
        initComponents();
        this.fleetDirectory=fleetDirectory;
        this.userProcessContainer = userProcessContainer;
        this.flight=flight;
        this.flightDirectory=flightDirectory;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fromlotxt = new javax.swing.JTextField();
        ADDButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tolotxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        whichpltxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create New Flight");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Flight Time:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, 30));

        timetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(timetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("FromLocation:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, 30));

        fromlotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(fromlotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 210, 30));

        ADDButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ADDButton.setText("Add Flight");
        ADDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDButtonActionPerformed(evt);
            }
        });
        add(ADDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 301, -1, -1));

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Flight Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 30));

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ToLocation:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 120, 30));

        tolotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(tolotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Which Airplane:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, 30));

        whichpltxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(whichpltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 210, 30));
    }// </editor-fold>//GEN-END:initComponents
    private void ADDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDButtonActionPerformed
    // TODO add your handling code here:
        Flight flight = flightDirectory.addFlight();
        try{
        flight.setName(nametxt.getText());
        flight.setTime(timetxt.getText());
        flight.setFromLocation(fromlotxt.getText());
        flight.setToLocation(tolotxt.getText());
        flight.setWhichPlane(whichpltxt.getText());
        JOptionPane.showMessageDialog(null, "Flight successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Wrong type!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            flightDirectory.removeFlight(flight);
        }
        
}//GEN-LAST:event_ADDButtonActionPerformed
  private void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlightJPanelPart ManageFlightJPanelPart = (ManageFlightJPanelPart) component;
        ManageFlightJPanelPart.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backButton1ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField fromlotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField timetxt;
    private javax.swing.JTextField tolotxt;
    private javax.swing.JTextField whichpltxt;
    // End of variables declaration//GEN-END:variables
}
