/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package UserInterface.AirlinerManagement.AirFlightManage;

import UserInterface.AirlinerManagement.Airfleetmanage.*;
import Business.Airliner;
import Business.Airplane;
import Business.Flight;
import UserInterface.AirlinerManagement.ManageAirlinerJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rushabh
 */
public class ViewFlightPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Flight flight;
   
    
    
    /** Creates new form CreateProductJPanel */
    public ViewFlightPanel(JPanel upc,Flight fli) {
        initComponents();
        userProcessContainer = upc;
        flight = fli;
        nameField.setText(fli.getName());
        flighttime.setText(fli.getTime());
        fromlo.setText(fli.getFromLocation());
        tolo.setText(fli.getToLocation());
        whichair.setText(fli.getWhichPlane());
    }

    
    public static String convertInteger(int i) {
        return Integer.toString(i);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fleetname = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        whichairliner = new javax.swing.JLabel();
        fromlo = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        flighttime = new javax.swing.JTextField();
        fleetnum = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        fleetnum1 = new javax.swing.JLabel();
        tolo = new javax.swing.JTextField();
        fleetnum2 = new javax.swing.JLabel();
        whichair = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Flight Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        fleetname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fleetname.setText("Flight Name:");
        add(fleetname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 30));

        nameField.setEditable(false);
        nameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 159, -1));

        whichairliner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        whichairliner.setText("FromLocation:");
        add(whichairliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, 30));

        fromlo.setEditable(false);
        fromlo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fromlo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(fromlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 159, -1));

        createButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createButton.setText("Update Flight");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 176, -1));

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        flighttime.setEditable(false);
        flighttime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        flighttime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(flighttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 159, -1));

        fleetnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fleetnum.setText("Flight Time:");
        add(fleetnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 30));

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 70, 30));

        fleetnum1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fleetnum1.setText("ToLocation:");
        add(fleetnum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 30));

        tolo.setEditable(false);
        tolo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tolo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(tolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 159, -1));

        fleetnum2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fleetnum2.setText("WhichAirplane:");
        add(fleetnum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, 30));

        whichair.setEditable(false);
        whichair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        whichair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(whichair, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 159, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
       nameField.setEditable(true);
       flighttime.setEditable(true);      
       fromlo.setEditable(true);
       tolo.setEditable(true);
       whichair.setEditable(false);
       saveButton.setEnabled(true);
}//GEN-LAST:event_createButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
      backAction();
    }//GEN-LAST:event_backButton1ActionPerformed

      private void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlightJPanelPart ManageFlightJPanelPart = (ManageFlightJPanelPart) component;
        ManageFlightJPanelPart.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:\
        try{
        flight.setName(nameField.getText());
        flight.setTime(flighttime.getText());
        flight.setFromLocation(fromlo.getText());
        flight.setToLocation(tolo.getText());
        flight.setWhichPlane(whichair.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Wrong type!");
        }
     
    }//GEN-LAST:event_saveButtonActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel fleetname;
    private javax.swing.JLabel fleetnum;
    private javax.swing.JLabel fleetnum1;
    private javax.swing.JLabel fleetnum2;
    private javax.swing.JTextField flighttime;
    private javax.swing.JTextField fromlo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField tolo;
    private javax.swing.JTextField whichair;
    private javax.swing.JLabel whichairliner;
    // End of variables declaration//GEN-END:variables
}
