/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package UserInterface.CustomerManagement;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.Booked;
import Business.BookedDirect;
import Business.Customer;
import Business.CustomerDirectory;
import Business.Fleet;
import Business.FleetDirectory;
import Business.Flight;
import Business.FlightDirectory;
import UserInterface.CustomerManagement.BookTickets.ManageFlightCustomerJPanelPart;
import UserInterface.CustomerManagement.Createinfo.CreateCustomerJPanel;
import UserInterface.CustomerManagement.UpdateInfo.SearchForCustomerInfoJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rushabh
 */
public class CustomerChooseJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Airliner airliner;
    AirlinerDirectory airlinerDirectory;
    Fleet fleet;
    FleetDirectory fleetDirectory;
    Airplane airplane;
    AirplaneDirectory airplaneDirectory;
    Flight flight;
    FlightDirectory flightDirectory;
    Customer customer;
    CustomerDirectory customerDirectory;
    String s="-1";
    Booked booked;
    BookedDirect bookedDirect;
//    MasterOrderCatalog masterOrderCatalog;
    
    /** Creates new form ProductManagerWorkAreaJPanel */
    //JPanel upc, Airliner a,AirlinerDirectory ad,FleetDirectory fleetDirectory,Airplane airplane,AirplaneDirectory airplaneDirectory, Flight flight, FlightDirectory flightDirectory,Customer customer,CustomerDirectory customerDirectory
    public CustomerChooseJPanel(JPanel upc,Airliner airliner,AirlinerDirectory airlinerDirectory,Fleet fleet,FleetDirectory fleetDirectory,Airplane airplane,AirplaneDirectory airplaneDirectory,Flight flight, FlightDirectory flightDirectory,Customer customer,CustomerDirectory customerDirectory,Booked booked,BookedDirect bookedDirect) {
        initComponents();
        userProcessContainer = upc;
        this.airliner=airliner;
        this.airlinerDirectory=airlinerDirectory;
        this.airplane=airplane;
        this.airplaneDirectory=airplaneDirectory;
        this.flight=flight;
        this.flightDirectory=flightDirectory;
        this.customer=customer;
        this.customerDirectory=customerDirectory;
        this.fleet=fleet;
        this.fleetDirectory=fleetDirectory;
        this.booked=booked;
        this.bookedDirect=bookedDirect;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageCustomer = new javax.swing.JButton();
        manageflight1 = new javax.swing.JButton();
        manageCustomer1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Customer Func ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        manageCustomer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageCustomer.setText("Create My Info");
        manageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerActionPerformed(evt);
            }
        });
        add(manageCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 230, -1));

        manageflight1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageflight1.setText("Book tickets");
        manageflight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageflight1ActionPerformed(evt);
            }
        });
        add(manageflight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 230, -1));

        manageCustomer1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageCustomer1.setText("Update My Info");
        manageCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomer1ActionPerformed(evt);
            }
        });
        add(manageCustomer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerActionPerformed
        // TODO add your handling code here:
        CreateCustomerJPanel mfjp = new CreateCustomerJPanel(userProcessContainer,customer,customerDirectory);
        userProcessContainer.add("CreateCustomerJPanel",mfjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomerActionPerformed

    private void manageflight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageflight1ActionPerformed
        // TODO add your handling code here:
//JPanel upc, Airliner p, FleetDirectory fleetDirectory,Airplane airplane,AirplaneDirectory airplaneDirectory,Flight flight,FlightDirectory flightDirectory,String s
        ManageFlightCustomerJPanelPart mfjp = new ManageFlightCustomerJPanelPart(userProcessContainer, airliner,airlinerDirectory,fleet,fleetDirectory,airplane,airplaneDirectory,flight,flightDirectory,customer,customerDirectory,bookedDirect,booked);
        userProcessContainer.add("ManageFlightJPanelPart",mfjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageflight1ActionPerformed

    private void manageCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomer1ActionPerformed
        // TODO add your handling code here:
        SearchForCustomerInfoJPanel mfjp = new SearchForCustomerInfoJPanel(userProcessContainer,customer,customerDirectory);
        userProcessContainer.add("CreateCustomerJPanel",mfjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomer1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCustomer;
    private javax.swing.JButton manageCustomer1;
    private javax.swing.JButton manageflight1;
    // End of variables declaration//GEN-END:variables
}
