/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainJFrame.java
 *
 * Created on Sep 28, 2012, 11:21:25 PM
 */

package UserInterface;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.Booked;
import Business.BookedDirect;
import Business.Customer;
import Business.CustomerDirectory;
import Business.Fleet;
import Business.FleetDirectory;
import Business.Flight;
import Business.FlightDirectory;
import UserInterface.AirlinerManagement.AirlinerChooseJPanel;
import UserInterface.CustomerManagement.CustomerChooseJPanel;
import UserInterface.TravelAgencyManagement.TravelAgencyJPanel;
import java.awt.CardLayout;

/**
 *
 * @author Rushabh
 */
public class MainJFrame extends javax.swing.JFrame {

    Airliner airliner;
    AirlinerDirectory airlinerDirectory;
    Fleet fleet;
    FleetDirectory fleetDirectory;
    Airplane airplane;
    AirplaneDirectory airplaneDirectory;
    Flight flight;
    FlightDirectory flightDirectory;
    Customer customer;
    CustomerDirectory customerDirectory;
    Booked booked;
    BookedDirect bookedDirect;
           
//    private MasterOrderCatalog moc;
    
    /** Creates new form MainJFrame */
    public MainJFrame() {
        initComponents();
        setSize(900, 600);
        setLocation(550, 250);
        //this.setExtendedState(MAXIMIZED_BOTH);
        airliner =new Airliner();
        airlinerDirectory = new AirlinerDirectory();
        fleet=new Fleet();
        fleetDirectory=new FleetDirectory();
        airplane= new Airplane();
        airplaneDirectory=new AirplaneDirectory();
        flight=new Flight();
        flightDirectory=new FlightDirectory();
        customer=new Customer();
        customerDirectory=new CustomerDirectory();
        booked=new Booked();
        bookedDirect=new BookedDirect();
                
        
//        moc = new MasterOrderCatalog();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        travelButton = new javax.swing.JButton();
        airButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(150);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        travelButton.setText("Travel Agency");
        travelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(travelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, -1));

        airButton.setText("Airliner");
        airButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airButtonActionPerformed(evt);
            }
        });
        jPanel1.add(airButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, -1));

        customerButton.setText("Customer");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(customerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 140, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void travelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelButtonActionPerformed
        // TODO add your handling code here:
        TravelAgencyJPanel travp = new TravelAgencyJPanel(userProcessContainer, airlinerDirectory);
        userProcessContainer.add("TravelAgencyJPanel",travp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_travelButtonActionPerformed

    private void airButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airButtonActionPerformed
        // TODO add your handling code here:
        AirlinerChooseJPanel la = new AirlinerChooseJPanel(userProcessContainer, airliner,airlinerDirectory,fleetDirectory,airplane,airplaneDirectory,flight,flightDirectory,customer,customerDirectory);
        userProcessContainer.add("AirlinerChooseJPanel",la );
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_airButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
//       TODO add your handling code here:
       CustomerChooseJPanel cwajp = new CustomerChooseJPanel(userProcessContainer, airliner,airlinerDirectory,fleet,fleetDirectory,airplane,airplaneDirectory,flight,flightDirectory,customer,customerDirectory,booked,bookedDirect);
       userProcessContainer.add("CustomerChooseJPanel",cwajp);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_customerButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airButton;
    private javax.swing.JButton customerButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton travelButton;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

}
