/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package UserInterface.AirlinerManagement.Airfleetmanage;

import Business.Airplane;
import Business.Airliner;
import Business.Fleet;
import Business.FleetDirectory;
import UserInterface.TravelAgencyManagement.ManageAirliners;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Rushabh
 */
public class CreateNewFleetJPanel extends javax.swing.JPanel {

    FleetDirectory fleetDirectory;
    JPanel userProcessContainer;
    
    /** Creates new form CreateProductJPanel */
    public CreateNewFleetJPanel(JPanel userProcessContainer, FleetDirectory fleetDirectory){
        initComponents();
        this.fleetDirectory=fleetDirectory;
        this.userProcessContainer = userProcessContainer;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fleetNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        whichair = new javax.swing.JTextField();
        ADDButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create New Fleet");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("FleetNum:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 100, 30));

        fleetNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(fleetNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Which Airliner:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 180, 120, 30));

        whichair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(whichair, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 210, 30));

        ADDButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ADDButton.setText("Add Fleet");
        ADDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDButtonActionPerformed(evt);
            }
        });
        add(ADDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 301, -1, 30));

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Fleet Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 30));

        nameField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 210, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void ADDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDButtonActionPerformed
    // TODO add your handling code here:
        Fleet fleet = fleetDirectory.addFleet();
        try{
        Long l=Long.parseLong(fleetNum.getText());
        
        fleet.setFleetName(nameField1.getText());
        fleet.setWhichAirliner(whichair.getText());
        fleet.setFleetNumber(l);
            JOptionPane.showMessageDialog(null, "Airliner successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Wrong type", "Warning", JOptionPane.INFORMATION_MESSAGE);
            fleetDirectory.removeFleet(fleet);
            
        }
       
}//GEN-LAST:event_ADDButtonActionPerformed
  private void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFleetJPanelPart ManageFleetJPanelPart = (ManageFleetJPanelPart) component;
        ManageFleetJPanelPart.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backButton1ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField fleetNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameField1;
    private javax.swing.JTextField whichair;
    // End of variables declaration//GEN-END:variables
}
