/*
 * ManageProductCatalogJPanel.java
 *
 * Created on September 24, 2008, 2:40 PM
 */
package UserInterface.CustomerManagement.BookTickets;
import Business.BookedDirect;
import Business.Booked;
import Business.Airplane;
import Business.Airliner;
import Business.AirlinerDirectory;
import Business.AirplaneDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import Business.Fleet;
import Business.FleetDirectory;
import Business.Flight;
import Business.FlightDirectory;
import Business.FlightSeats;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rushabh
 */
public class BookSeatJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Airliner airliner;
    AirlinerDirectory airlinerDirectory;
    Fleet fleet;
    FleetDirectory fleetDirectory;
    Flight flight;
    FlightDirectory flightDirectory;
    Airplane airplane;
    AirplaneDirectory airplaneDirectory;
    Customer customer;
    CustomerDirectory customerDirectory;
    String s;
    BookedDirect bookedDirect;
    Booked booked;
    ArrayList<Booked> bo;
    long customerid;

    /** Creates new form ManageProductCatalogJPanel */
    
//    userProcessContainer,p ,fleetDirectory,airplane,airplaneDirectory,flight,flightDirectory,s
    public BookSeatJPanel(JPanel upc, Airliner p,AirlinerDirectory airlinerDirectory,Fleet fleet, FleetDirectory fleetDirectory,Airplane airplane,AirplaneDirectory airplaneDirectory,Flight flight,FlightDirectory flightDirectory,Customer customer,CustomerDirectory customerDirectory,BookedDirect bookedDirect,Booked booked,String s,long customerid) {
        initComponents();
        setSize(550, 550);
        ArrayList<Booked> bo=new ArrayList<Booked>();
        this.airlinerDirectory=airlinerDirectory;
        this.fleet=fleet;
        this.fleetDirectory=fleetDirectory;
        this.flight=flight;
        this.flightDirectory=flightDirectory;
        this.airplane=airplane;
        this.airplaneDirectory=airplaneDirectory;
        this.customer=customer;
        this.customerDirectory=customerDirectory;
        this.booked=booked;
        this.bookedDirect=bookedDirect;
        userProcessContainer = upc;
        this.s=s;
        this.customerid=customerid;
        this.flight=flight;
        this.customerDirectory=customerDirectory;
        jLabel8.setText(s);
        jLabel11.setText(String.valueOf(customerid));
        //bo=classify();
        refreshTable();

        
        //nametxt.setText(airliner.getAirlinerName());
//        refreshTable();
        
    }
    
    public void refreshTable() {
        int rowCount = BookedList.getRowCount();
        DefaultTableModel model = (DefaultTableModel)BookedList.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
            
        for(Booked p :bookedDirect.searchBooked(s)) {
            Object row[] = new Object[2];
            row[0] = p.getRow();
            row[1] = p.getCol();
            model.addRow(row);
            }
            
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    BookSeatJPanel(JPanel userProcessContainer, Flight flight) {
        initComponents();
        setSize(550, 550);
        userProcessContainer = userProcessContainer;
        //this.s=s;
        //this.fli=flight;
        //jLabel8.setText(s);
        this.flight=flight;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton4 = new javax.swing.JButton();
        BookButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jTextField87 = new javax.swing.JTextField();
        jTextField88 = new javax.swing.JTextField();
        jTextField89 = new javax.swing.JTextField();
        jTextField90 = new javax.swing.JTextField();
        jTextField91 = new javax.swing.JTextField();
        jTextField92 = new javax.swing.JTextField();
        jTextField93 = new javax.swing.JTextField();
        jTextField94 = new javax.swing.JTextField();
        jTextField95 = new javax.swing.JTextField();
        jTextField96 = new javax.swing.JTextField();
        jTextField97 = new javax.swing.JTextField();
        jTextField98 = new javax.swing.JTextField();
        jTextField99 = new javax.swing.JTextField();
        jTextField100 = new javax.swing.JTextField();
        jTextField101 = new javax.swing.JTextField();
        jTextField102 = new javax.swing.JTextField();
        jTextField103 = new javax.swing.JTextField();
        jTextField104 = new javax.swing.JTextField();
        Comcol = new javax.swing.JComboBox();
        ComRow = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookedList = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Book your Seat");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        backButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });
        add(backButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, 110, -1));

        BookButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BookButton3.setText("BookSeat >>");
        BookButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButton3ActionPerformed(evt);
            }
        });
        add(BookButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 740, 220, -1));

        jLabel2.setText("columns:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel6.setText("rows:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel3.setText("Aisle");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        jLabel4.setText("Windows");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jLabel5.setText("Windows");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jTextField3.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField3.setText("3");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 20));

        jTextField4.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField4.setText("1");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 20));

        jTextField5.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField5.setText("2");
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 20));

        jTextField7.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField7.setText("2");
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 20));

        jTextField10.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField10.setText("3");
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 20));

        jTextField13.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField13.setText("4");
        add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, 20));

        jTextField16.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField16.setText("5");
        add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, 20));

        jTextField19.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField19.setText("6");
        add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, 20));

        jTextField22.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField22.setText("7");
        add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, 20));

        jTextField25.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField25.setText("8");
        add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, 20));

        jTextField28.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField28.setText("9");
        add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, 20));

        jTextField31.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField31.setText("10");
        add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, 20));

        jTextField34.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField34.setText("11");
        add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, 20));

        jTextField37.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField37.setText("12");
        add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, 20));

        jTextField40.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField40.setText("13");
        add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, 20));

        jTextField43.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField43.setText("14");
        add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, 20));

        jTextField46.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField46.setText("15");
        add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, 20));

        jTextField49.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField49.setText("16");
        add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, 20));

        jTextField52.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField52.setText("17");
        add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, 20));

        jTextField55.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField55.setText("18");
        add(jTextField55, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, 20));

        jTextField58.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField58.setText("19");
        add(jTextField58, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, -1, 20));

        jTextField61.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField61.setText("20");
        add(jTextField61, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, -1, 20));

        jTextField64.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField64.setText("21");
        add(jTextField64, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, -1, 20));

        jTextField67.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField67.setText("22");
        add(jTextField67, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 690, -1, 20));

        jTextField70.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField70.setText("23");
        add(jTextField70, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 720, -1, 20));

        jTextField73.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField73.setText("24");
        add(jTextField73, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 750, -1, 20));

        jTextField76.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField76.setText("25");
        add(jTextField76, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 780, -1, 20));

        jTextField78.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField78.setText("1");
        add(jTextField78, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, 20));

        jTextField79.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField79.setText("2");
        add(jTextField79, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, 20));

        jTextField80.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField80.setText("3");
        add(jTextField80, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, 20));

        jTextField81.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField81.setText("4");
        add(jTextField81, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, 20));

        jTextField82.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField82.setText("5");
        add(jTextField82, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, 20));

        jTextField83.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField83.setText("6");
        add(jTextField83, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, 20));

        jTextField84.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField84.setText("7");
        add(jTextField84, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, 20));

        jTextField85.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField85.setText("8");
        add(jTextField85, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, 20));

        jTextField86.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField86.setText("9");
        add(jTextField86, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, 20));

        jTextField87.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField87.setText("10");
        add(jTextField87, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, 20));

        jTextField88.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField88.setText("11");
        add(jTextField88, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, 20));

        jTextField89.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField89.setText("12");
        add(jTextField89, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, 20));

        jTextField90.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField90.setText("13");
        add(jTextField90, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, 20));

        jTextField91.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField91.setText("14");
        add(jTextField91, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, 20));

        jTextField92.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField92.setText("15");
        add(jTextField92, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, 20));

        jTextField93.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField93.setText("16");
        add(jTextField93, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, 20));

        jTextField94.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField94.setText("17");
        add(jTextField94, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, 20));

        jTextField95.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField95.setText("18");
        add(jTextField95, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, 20));

        jTextField96.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField96.setText("19");
        add(jTextField96, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, -1, 20));

        jTextField97.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField97.setText("20");
        add(jTextField97, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, -1, 20));

        jTextField98.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField98.setText("21");
        add(jTextField98, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, -1, 20));

        jTextField99.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField99.setText("22");
        add(jTextField99, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 690, -1, 20));

        jTextField100.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField100.setText("23");
        add(jTextField100, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 720, -1, 20));

        jTextField101.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField101.setText("24");
        add(jTextField101, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 750, -1, 20));

        jTextField102.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField102.setText("25");
        add(jTextField102, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 780, -1, 20));

        jTextField103.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField103.setText("3");
        add(jTextField103, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, 20));

        jTextField104.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jTextField104.setText("4");
        add(jTextField104, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, 20));

        Comcol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        Comcol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComcolActionPerformed(evt);
            }
        });
        add(Comcol, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 80, 30));

        ComRow.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));
        ComRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComRowActionPerformed(evt);
            }
        });
        add(ComRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Flight:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        BookedList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "row", "col"
            }
        ));
        jScrollPane2.setViewportView(BookedList);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 140, 440));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Booked Seats List");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("CustomerId:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("jLabel8");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
         Component component = componentArray[componentArray.length - 1];
         ManageFlightCustomerJPanelPart manageAirplaneDirectoryJPanel = (ManageFlightCustomerJPanelPart) component;
         manageAirplaneDirectoryJPanel.refreshTable();
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backButton4ActionPerformed

    private void BookButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButton3ActionPerformed
        // TODO add your handling code here:
        int row=ComRow.getSelectedIndex()+1;
        int col=Comcol.getSelectedIndex()+1;
        int[][] a=flight.getSeats();
        if(flight.isAvailable(row, col,a)){
            flight.book(row, col, a);
            booked = bookedDirect.addBooked();
            booked.setRow(row);
            booked.setCol(col);
            booked.setWhichflight(s);
            refreshTable();
            JOptionPane.showMessageDialog(null,"Book complete!"+"\n"+ "Seat:"+row+col+"\n"+"flight:"+s+"\n"+"Customer:"+customerid);
        }else{
            JOptionPane.showMessageDialog(null, "The seat has been booked!");
        }
    }//GEN-LAST:event_BookButton3ActionPerformed

    private void ComcolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComcolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComcolActionPerformed

    private void ComRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComRowActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookButton3;
    private javax.swing.JTable BookedList;
    private javax.swing.JComboBox ComRow;
    private javax.swing.JComboBox Comcol;
    private javax.swing.JButton backButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField100;
    private javax.swing.JTextField jTextField101;
    private javax.swing.JTextField jTextField102;
    private javax.swing.JTextField jTextField103;
    private javax.swing.JTextField jTextField104;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField87;
    private javax.swing.JTextField jTextField88;
    private javax.swing.JTextField jTextField89;
    private javax.swing.JTextField jTextField90;
    private javax.swing.JTextField jTextField91;
    private javax.swing.JTextField jTextField92;
    private javax.swing.JTextField jTextField93;
    private javax.swing.JTextField jTextField94;
    private javax.swing.JTextField jTextField95;
    private javax.swing.JTextField jTextField96;
    private javax.swing.JTextField jTextField97;
    private javax.swing.JTextField jTextField98;
    private javax.swing.JTextField jTextField99;
    // End of variables declaration//GEN-END:variables
}
